export default [
	{
		name: 'Microbe Mission',
		inRotation: true,
		building: false,
		impound: false,
		resources: '1 page front and back',
		currentTopic: '',
		highScoreWins: true,
		stateEvent: false,
		category: 'bio',
		division: 'BC',
	},
	{
		name: 'Disease Detectives',
		inRotation: true,
		building: false,
		impound: false,
		resources: '1 page front and back',
		division: 'BC',
		stateEvent: false,
		highScoreWins: true,
		currentTopic: '',
		category: 'bio',
	},
	{
		name: 'Ecology',
		inRotation: true,
		building: false,
		impound: false,
		resources: '1 page front and back',
		currentTopic: '',
		highScoreWins: true,
		stateEvent: false,
		category: 'bio',
		division: 'BC',
	},
	{
		name: 'Invasive Species',
		inRotation: false,
		building: false,
		impound: false,
		resources: '1 binder',
		topic: '',
		stateEvent: false,
	},
	{
		name: 'Astronomy',
		inRotation: true,
		building: false,
		impound: false,
		resources: '2 laptops, 2 binders, or one of each',
		division: 'C',
		stateEvent: false,
		highScoreWins: true,
		currentTopic: '',
		category: 'earth',
	},
	{
		name: 'Dynamic Planet',
		inRotation: true,
		building: false,
		impound: false,
		resources: '4 pages front and back',
		topic: 'Tectonics',
		stateEvent: false,
		currentTopic: 'Tectonics',
		highScoreWins: true,
		category: 'earth',
		division: 'BC',
	},
	{
		name: 'Rocks & Minerals',
		inRotation: true,
		building: false,
		impound: false,
		resources: '1 magnifying glass, 1 field guide, and 1 binder',
		currentTopic: '',
		highScoreWins: true,
		stateEvent: false,
		category: 'earth',
		division: 'BC',
	},
	{
		name: 'Remote Sensing',
		inRotation: true,
		building: false,
		impound: false,
		resources: '1 binder',
		currentTopic: '',
		highScoreWins: true,
		stateEvent: false,
		category: 'earth',
		division: 'C',
	},
	{
		name: 'Materials Science',
		inRotation: true,
		building: true,
		impound: false,
		resources: '1 binder',
		currentTopic: '',
		highScoreWins: true,
		stateEvent: false,
		category: 'phys/chem',
		division: 'C',
	},
	{
		name: 'Hovercraft',
		inRotation: true,
		building: true,
		impound: true,
		resources: '1 binder',
		division: 'BC',
		stateEvent: false,
		highScoreWins: true,
		currentTopic: '',
		category: 'building',
	},
	{
		name: 'Chemistry Lab',
		inRotation: true,
		building: false,
		impound: false,
		resources: '5 pages front and back',
		topic: 'Thermodynamics, Physical properties',
		stateEvent: false,
		division: 'C',
		highScoreWins: true,
		currentTopic: 'Thermodynamics, Physical properties',
		category: 'phys/chem',
	},
	{
		name: 'Forensics',
		inRotation: true,
		building: false,
		impound: false,
		resources: '1 binder',
		currentTopic: '',
		highScoreWins: true,
		stateEvent: false,
		category: 'phys/chem',
		division: 'C',
	},
	{
		name: 'WiFi Lab',
		inRotation: true,
		building: true,
		impound: true,
		resources: '5 pages front and back',
		topic: '',
		stateEvent: true,
		currentTopic: '',
		highScoreWins: true,
		category: 'building',
		division: 'C',
	},
	{
		name: 'Towers',
		inRotation: true,
		building: true,
		impound: false,
		resources: 'State 2016 bridge resources',
		currentTopic: '',
		highScoreWins: true,
		stateEvent: false,
		category: 'building',
		division: 'BC',
	},
	{
		name: 'Hydrogeology',
		inRotation: false,
		building: false,
		impound: false,
		resources: '1 page front and back',
		topic: '',
		stateEvent: false,
	},
	{
		name: 'Robot Arm',
		inRotation: false,
		building: true,
		impound: false,
		resources: '',
		topic: '',
		stateEvent: false,
	},
	{
		name: 'Wind Power',
		inRotation: false,
		building: true,
		impound: true,
		resources: '1 binder',
		topic: '',
		stateEvent: false,
	},
	{
		name: 'Helicopters',
		inRotation: true,
		building: true,
		impound: false,
		currentTopic: '',
		highScoreWins: true,
		stateEvent: false,
		category: 'building',
		division: 'C',
	},
	{
		name: 'Write It Do It',
		inRotation: true,
		building: false,
		impound: false,
		currentTopic: '',
		highScoreWins: true,
		stateEvent: false,
		category: 'inquiry',
		division: 'BC',
	},
	{
		name: 'Electric Vehicle',
		inRotation: false,
		building: true,
		impound: true,
		resources: '',
		topic: '',
		stateEvent: false,
	},
	{
		inRotation: true,
		currentTopic: '',
		highScoreWins: true,
		stateEvent: false,
		impound: false,
		category: 'inquiry',
		division: 'BC',
		name: 'Experimental Design',
	},
	{
		name: 'Game On',
		inRotation: true,
		building: false,
		impound: false,
		currentTopic: '',
		highScoreWins: true,
		stateEvent: false,
		category: 'inquiry',
		division: 'C',
	},
	{
		name: "We've Got Your Number",
		inRotation: true,
		building: false,
		impound: false,
		resources: '',
		topic: '',
		stateEvent: true,
		currentTopic: '',
		highScoreWins: true,
		category: 'inquiry',
		division: 'BC',
	},
	{
		name: 'Roller Coaster',
		inRotation: true,
		building: true,
		impound: true,
		currentTopic: '',
		highScoreWins: true,
		stateEvent: false,
		category: 'building',
		division: 'B',
	},
	{
		name: 'Fermi Questions',
		inRotation: true,
		building: false,
		impound: false,
		currentTopic: '',
		highScoreWins: true,
		stateEvent: false,
		category: 'inquiry',
		division: 'C',
	},
	{
		name: 'Optics',
		inRotation: true,
		building: false,
		impound: false,
		resources: '1 binder',
		currentTopic: '',
		highScoreWins: true,
		stateEvent: false,
		category: 'phys/chem',
		division: 'BC',
	},
	{
		name: 'Mission Possible',
		topic: '',
		resources: '',
		stateEvent: false,
		impound: true,
		building: true,
		inRotation: true,
		__v: 0,
		currentTopic: '',
		highScoreWins: true,
		category: 'building',
		division: 'C',
	},
	{
		name: 'Herpetology',
		topic: '',
		resources: '1 binder',
		stateEvent: false,
		impound: false,
		building: false,
		inRotation: true,
		__v: 0,
		currentTopic: '',
		highScoreWins: true,
		category: 'bio',
		division: 'BC',
	},
	{
		name: 'Anatomy & Physiology',
		resources: '',
		stateEvent: false,
		impound: false,
		building: false,
		inRotation: true,
		__v: 0,
		division: 'BC',
		highScoreWins: true,
		currentTopic: '',
		category: 'bio',
	},
	{
		name: 'Mechathlon',
		highScoreWins: true,
		topics: [],
		stateEvent: true,
		impound: true,
		building: false,
		inRotation: true,
		division: 'C',
		__v: 0,
		currentTopic: '',
		category: 'building',
	},
	{
		name: 'Code Busters',
		highScoreWins: true,
		topics: [],
		stateEvent: true,
		impound: false,
		building: false,
		inRotation: true,
		division: 'C',
		category: 'inquiry',
		__v: 0,
		currentTopic: '',
	},
	{
		name: 'Science Word',
		highScoreWins: true,
		topics: [],
		stateEvent: true,
		impound: false,
		building: false,
		inRotation: true,
		division: 'C',
		category: 'inquiry',
		__v: 0,
		currentTopic: '',
	},
	{
		name: 'Naked Egg Drop',
		highScoreWins: true,
		topics: [],
		stateEvent: true,
		impound: true,
		building: false,
		inRotation: true,
		division: 'B',
		category: 'building',
		__v: 0,
		currentTopic: '',
	},
	{
		name: 'Indoor Bottle Rockets',
		highScoreWins: true,
		topics: [],
		stateEvent: true,
		impound: false,
		building: false,
		inRotation: true,
		division: 'B',
		category: 'building',
		__v: 0,
		currentTopic: '',
	},
	{
		name: 'Density',
		highScoreWins: true,
		topics: [],
		stateEvent: true,
		impound: false,
		building: false,
		inRotation: true,
		division: 'B',
		category: 'phys/chem',
		__v: 0,
		currentTopic: '',
	},
	{
		name: 'Mystery Architecture',
		highScoreWins: true,
		topics: [],
		stateEvent: false,
		impound: false,
		building: false,
		inRotation: true,
		division: 'B',
		category: 'inquiry',
		__v: 0,
		currentTopic: '',
	},
	{
		name: 'Potions and Poisons',
		highScoreWins: true,
		topics: [],
		stateEvent: false,
		impound: false,
		building: false,
		inRotation: true,
		division: 'B',
		category: 'phys/chem',
		__v: 0,
		currentTopic: '',
	},
	{
		name: 'Road Scholar',
		highScoreWins: true,
		topics: [],
		stateEvent: false,
		impound: false,
		building: false,
		inRotation: true,
		division: 'B',
		category: 'building',
		__v: 0,
		currentTopic: '',
	},
	{
		name: 'Meteorology',
		highScoreWins: true,
		topics: [],
		stateEvent: false,
		impound: false,
		building: false,
		inRotation: true,
		division: 'B',
		category: 'earth',
		__v: 0,
		currentTopic: '',
	},
	{
		name: 'Solar System',
		highScoreWins: true,
		topics: [],
		stateEvent: false,
		impound: false,
		building: false,
		inRotation: true,
		division: 'B',
		category: 'earth',
		__v: 0,
		currentTopic: '',
	},
	{
		name: 'Wright Stuff',
		highScoreWins: true,
		topics: [],
		stateEvent: false,
		impound: false,
		building: false,
		inRotation: true,
		division: 'B',
		category: 'building',
		__v: 0,
		currentTopic: '',
	},
	{
		name: 'Battery Buggy',
		highScoreWins: false,
		topics: [],
		stateEvent: false,
		impound: false,
		building: false,
		inRotation: true,
		division: 'B',
		category: 'building',
		__v: 0,
		currentTopic: '',
	},
	{
		name: 'Crime Busters',
		highScoreWins: true,
		topics: [],
		stateEvent: false,
		impound: false,
		building: false,
		inRotation: true,
		division: 'B',
		category: 'phys/chem',
		__v: 0,
		currentTopic: '',
	},
	{
		name: 'Fast Facts',
		highScoreWins: true,
		topics: [],
		stateEvent: false,
		impound: false,
		building: false,
		inRotation: true,
		division: 'B',
		category: 'inquiry',
		__v: 0,
		currentTopic: '',
	},
	{
		name: 'Picture This',
		inRotation: true,
		building: false,
		impound: false,
		resources: '',
		topic: '',
		stateEvent: true,
		currentTopic: '',
		highScoreWins: true,
		category: 'inquiry',
		division: 'B',
	},
	{
		name: 'Mousetrap Vehicle',
		topic: '',
		resources: '',
		stateEvent: false,
		impound: true,
		building: true,
		inRotation: true,
		__v: 0,
		currentTopic: '',
		highScoreWins: false,
		category: 'building',
		division: 'C',
	},
	{
		name: 'Thermodynamics',
		topic: '',
		resources: '',
		stateEvent: false,
		impound: false,
		building: true,
		inRotation: true,
		__v: 0,
		currentTopic: '',
		highScoreWins: true,
		category: 'phys/chem',
		division: 'BC',
	},
]
